name: TerrainControl
version: 2.0.6
description: Generates a worlds.
authors: ['Khorn']
main: com.Khorn.TerrainControl.Bukkit.TCPlugin
load: startup
commands:
    tc:
        description: TerrainControl commands
        usage: |
              /<command> <check> [world] - Checks TC is enable for this world.
              /<command> <reload> [world] - Reload config
              /<command> <biome> [-f] - Show current chunk biome and block stats
        aliases: [terraincontrol]
