name: PhoenixTerrainMod
version: 0.9
description: Generates a worlds.
authors: ['Khorn', 'R-T-B']
main: com.Khorn.PTMBukkit.PTMPlugin
load: startup
commands:
    ptm:
        description: Phoenix Terrain Mod commands
        usage: |
              /<command> <check> [world] - Checks PTM is enable for this world.
              /<command> <reload> [world] - Reload config
              /<command> <biome> [-f] - Show current chunk biome and block stats